apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: backend
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/ibouaida/backend.git
        targetRevision: HEAD
        path: manifests
    
    destination:
        server: https://kubernetes.default.svc
        namespace: ml-project
    syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
            selfHeal: true
            prune: true
 